### ISSUE TITLE
Add done / todo item

### ISSUE THREAD

**Issue by matjack1** [TiC-1/Week8_Skills#29]
- [ ] show contextual info in every node
- [ ] add checkboxes with done / todo in contextual info
- [ ] add actions on checkboxes to mark as done / todo
- [ ] when node is to do => colour orange
- [ ] when node is done => colour green
- [ ] node colour depends on children
